# Generated by Django 5.2.1 on 2025-06-08 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_recorded", models.DateTimeField(auto_now_add=True)),
                (
                    "date_measured",
                    models.DateField(help_text="Date when the measurements were taken"),
                ),
                (
                    "systolic_bp",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Systolic blood pressure (mmHg)",
                        null=True,
                    ),
                ),
                (
                    "diastolic_bp",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Diastolic blood pressure (mmHg)",
                        null=True,
                    ),
                ),
                (
                    "total_cholesterol",
                    models.PositiveIntegerField(
                        blank=True, help_text="Total cholesterol (mg/dL)", null=True
                    ),
                ),
                (
                    "ldl",
                    models.PositiveIntegerField(
                        blank=True, help_text="LDL (mg/dL)", null=True
                    ),
                ),
                (
                    "hdl",
                    models.PositiveIntegerField(
                        blank=True, help_text="HDL (mg/dL)", null=True
                    ),
                ),
                (
                    "triglycerides",
                    models.PositiveIntegerField(
                        blank=True, help_text="Triglycerides (mg/dL)", null=True
                    ),
                ),
                (
                    "glucose",
                    models.PositiveIntegerField(
                        blank=True, help_text="Fasting glucose (mg/dL)", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_measured"],
            },
        ),
    ]
