# Generated by Django 5.2.1 on 2025-06-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="healthrecord",
            options={},
        ),
        migrations.RemoveField(
            model_name="healthrecord",
            name="date_recorded",
        ),
        migrations.RemoveField(
            model_name="healthrecord",
            name="hdl",
        ),
        migrations.RemoveField(
            model_name="healthrecord",
            name="ldl",
        ),
        migrations.RemoveField(
            model_name="healthrecord",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="healthrecord",
            name="total_cholesterol",
        ),
        migrations.RemoveField(
            model_name="healthrecord",
            name="triglycerides",
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="abdominal_sono",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="afp",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="ag_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="albumin",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="alk_phosphatase",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="basophil",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="bc_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="bilirubin_indirect",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="blast",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="bmi",
            field=models.DecimalField(
                blank=True, decimal_places=2, editable=False, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="body_fat_mass",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="body_minerals",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="body_protein",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="body_water",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="bun",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="ca199",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="cea",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="chest_xray_ct",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="cholesterol_hdl",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="cholesterol_ldl",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="cholesterol_total",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="creatinine",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="d_bilirubin",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="ecw_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="egfr",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="free_t4",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="fundus",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="gastroscopy",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="ggtp",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="globulin",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="hbsab",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="hbsag",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="hct",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="height",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="hemoglobin",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="ldh",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="left_arm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="left_leg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="male_pelvis_sono",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="mch",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="mchc",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="mcv",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="metamyelocyte",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="mpv",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="myelocyte",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="nucleated_rbc",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="ocular_tension",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="pct",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="pdw",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="percent_body_fat",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="platelet",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="promyelocyte",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="psa",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="ra_factor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="rbc",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="rdw",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="right_arm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="right_leg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="rpr",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="sgot_ast",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="sgpt_alt",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="skeletal_muscle_mass",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="stool_occult_blood",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="t_bilirubin",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="thyroid_sono",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="total_protein",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="triglyceride",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="trunk",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="tsh",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="uric_acid",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="urine_bacteria",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="urine_bilirubin",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="urine_blood",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="urine_casts",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="urine_color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="urine_crystals",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="urine_epithelial_cell",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="urine_glucose",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="urine_ketone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="urine_nitrite",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="urine_ph",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="urine_protein",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="urine_rbc",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="urine_urobilinogen",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="urine_wbc",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="waist_line",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="wbc",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="date_measured",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="diastolic_bp",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="glucose",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="systolic_bp",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
