# Generated by Django 5.2.1 on 2025-06-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health_data", "0002_alter_healthrecord_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="healthrecord",
            name="ocular_tension",
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="ocular_tension_left",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="ocular_tension_right",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
