# Generated by Django 5.2.1 on 2025-06-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health_data", "0003_remove_healthrecord_ocular_tension_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthrecord",
            name="hearing",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
