# Generated by Django 5.2.1 on 2025-06-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health_data", "0004_healthrecord_hearing"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthrecord",
            name="ekg",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
