# Generated by Django 5.2.1 on 2025-06-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health_data", "0005_healthrecord_ekg"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthrecord",
            name="band",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="eosinophil",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="lymphocyte",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="monocyte",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="segment",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="urine_other",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="urine_sg",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="rpr",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
