# Generated by Django 5.2.1 on 2025-06-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health_data", "0006_healthrecord_band_healthrecord_eosinophil_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthrecord",
            name="height",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
