# Generated by Django 5.2.1 on 2025-06-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health_data", "0007_alter_healthrecord_height"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthrecord",
            name="ecw_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=5, null=True
            ),
        ),
    ]
