# Generated by Django 5.2.1 on 2025-06-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_data', '0009_alter_healthrecord_urine_sg'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='anti_hcv',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='autonomic_nervous_activity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='autonomic_nervous_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='bone_density',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='c_reactive_protein',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='c_spine_ct',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='calcium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='carotid_artery_sono',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='chloride',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='ck_mb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='hav_lgm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='hb_a1c',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='l_spine_ct',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='phosphorus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='potassium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='sodium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='stress_index',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='ra_factor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
