# Generated by Django 5.2.1 on 2025-06-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_data', '0011_healthrecord_absolute_basophil_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='urine_urobilinogen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
