# Generated by Django 5.2.1 on 2025-06-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_data', '0013_alter_healthrecord_urine_sg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='tsh',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
