# Generated by Django 5.2.1 on 2025-06-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_data', '0016_healthfieldrange'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthfieldrange',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
